# Generated by Django 4.2.6 on 2023-12-26 08:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0002_remove_expense_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={"ordering": ["-created_at"]},
        ),
    ]
